In [23]:
import numpy as np 
import pandas as pd 
import os
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
#SK Learn Libraries
import sklearn
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier   #1vs1 & 1vsRest Classifiers
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

import gc

In [24]:
dataset = pd.read_csv(r'C:\Users\HP\Desktop\ramp_d.csv')
dataset

beam_current  beam_energy    bpi2_x    bpi3_x   bpi27_z   bpi32_z  \
0     123.515023   545.320370 -7.498176 -7.092416 -0.762908  0.980314   
1     149.536207   699.055126  1.671586  1.991034  0.693276 -0.484345   
2     149.258421   897.739982  1.756947  2.027000  0.747211 -0.290421   
3     149.161818  1098.674273  1.827727  2.145818  0.733636 -0.134636   
4     149.102000  1298.582450  1.971600  2.352600  0.691200 -0.013800   
5     149.019000  1499.223220 -0.414300 -0.163000 -0.346000  1.257700   
6     148.968000  1699.855480 -1.010300 -0.511400 -0.474600  1.432500   
7     148.920909  1900.979145 -1.150182 -0.566000 -0.517727  1.461091   
8     148.884167  2100.929525 -1.359833 -0.617417 -0.556583  1.465583   
9     148.800000  2300.308533 -1.408200 -0.398133 -0.449200  1.441667   
10    147.862997  2498.827111 -2.461520 -1.027493  0.429317  1.762029   
11     80.707327   545.332460 -7.666564 -7.226145 -0.820269  1.032728   
12    144.025517   700.013049  1.232655  1.619793  0.615690 -0.437517   
13    143.812000   898.519567  1.313350  1.639600  0.668200 -0.240600   
14    143.731667  1098.499517  1.386250  1.759000  0.654167 -0.083000   
15    143.661818  1299.602800  1.507091  1.935545  0.612909  0.041364   
16    143.618000  1502.215590 -0.981500 -0.651800 -0.465200  1.357800   
17    143.592727  1700.922045 -1.474636 -0.907818 -0.531818  1.480182   
18    143.550000  1899.170618 -1.633273 -0.965273 -0.587727  1.506455   

     bpi35_x   bpi38_x   bpi43_z   bpi45_z   bpi46_z   bpi56_x  label  
0  -0.376128  0.817139  0.796814 -0.565724  0.281941  3.760189      1  
1   3.208552 -4.715621 -0.342724 -3.750552 -2.198448 -0.811759      2  
2   3.614263 -5.371632 -0.401105 -3.242789 -1.792000 -0.889579      2  
3   4.168636 -6.034455 -0.397727 -2.930727 -1.555727 -1.063182      2  
4   4.596300 -6.567900 -0.380400 -2.715600 -1.405700 -1.264400      3  
5   1.924600 -1.496000 -0.129200 -1.178200 -0.032300 -0.737900      3  
6   0.950100 -0.772900 -0.227000 -0.860600  0.275300 -0.657000      3  
7   0.700364 -0.526364 -0.238636 -0.882818  0.263727 -0.786455      3  
8   0.463833 -0.565417 -0.244833 -0.912750  0.231417 -0.647750      4  
9   0.613200 -1.124600 -0.318800 -0.908600  0.251467 -0.469933      4  
10  1.153034 -0.866371  2.450866 -0.230293  0.234600  0.763579      4  
11  0.013750  0.452209  0.971554 -0.552409  0.175465  3.994206      1  
12  3.330345 -4.846552 -0.153034 -3.706552 -2.305793 -0.495586      2  
13  3.817450 -5.495050 -0.213850 -3.225250 -1.913050 -0.565150      2  
14  4.329583 -6.147667 -0.216667 -2.912500 -1.679583 -0.732917      2  
15  4.688818 -6.647909 -0.200818 -2.704727 -1.528636 -0.919000      3  
16  1.960400 -1.386600  0.014400 -1.088700 -0.083200 -0.391500      3  
17  1.118636 -0.861727 -0.036182 -0.837000  0.159909 -0.324273      3  
18  0.856364 -0.616727 -0.038364 -0.862091  0.148727 -0.443909      3

In [25]:
#Finding difference between max and min of each attribute.
list_mn=[]
list_columns=['bpi2_x','bpi3_x','bpi27_z','bpi32_z','bpi35_x','bpi38_x','bpi43_z','bpi45_z','bpi46_z','bpi56_x']
for i in list_columns:
    p=dataset[i].max()
    q=dataset[i].min()
    print(p-q)
    list_mn.append(p-q)
list_mn

9.638163844
9.578745080000001
1.567479176
2.246373799
5.064946659
7.465047685
2.851971397
3.5202590170000003
2.587733922
5.258606407


[9.638163844,
 9.578745080000001,
 1.567479176,
 2.246373799,
 5.064946659,
 7.465047685,
 2.851971397,
 3.5202590170000003,
 2.587733922,
 5.258606407]

In [26]:
len(list_mn)

10

In [27]:
#This is the list which consists of max-min of all bpix.
listx_mn=[]
y=len(list_mn)
i=0
while i < 10:
    listx_mn.append(list_mn[i])
    i=i+1
    
listx_mn.sort(reverse=True)

In [28]:
len(listx_mn)

10

In [29]:
#This is the list of max-min of all bpiy.
listy_mn=[]
i=1
while i < 10:
    listy_mn.append(list_mn[i])
    i=i+2
    

listy_mn

[9.578745080000001, 2.246373799, 7.465047685, 3.5202590170000003, 5.258606407]

In [30]:
#Sorting all max-min values in desc order of bpix's.
listx_mn.sort(reverse=True)
print(listx_mn)

[9.638163844, 9.578745080000001, 7.465047685, 5.258606407, 5.064946659, 3.5202590170000003, 2.851971397, 2.587733922, 2.246373799, 1.567479176]


In [31]:
#Sorting all max-min values in desc order of bpiy's.
listy_mn.sort(reverse=True)
print(listy_mn)

[9.578745080000001, 7.465047685, 5.258606407, 3.5202590170000003, 2.246373799]


In [32]:
#Useful dataset.
dataset

beam_current  beam_energy    bpi2_x    bpi3_x   bpi27_z   bpi32_z  \
0     123.515023   545.320370 -7.498176 -7.092416 -0.762908  0.980314   
1     149.536207   699.055126  1.671586  1.991034  0.693276 -0.484345   
2     149.258421   897.739982  1.756947  2.027000  0.747211 -0.290421   
3     149.161818  1098.674273  1.827727  2.145818  0.733636 -0.134636   
4     149.102000  1298.582450  1.971600  2.352600  0.691200 -0.013800   
5     149.019000  1499.223220 -0.414300 -0.163000 -0.346000  1.257700   
6     148.968000  1699.855480 -1.010300 -0.511400 -0.474600  1.432500   
7     148.920909  1900.979145 -1.150182 -0.566000 -0.517727  1.461091   
8     148.884167  2100.929525 -1.359833 -0.617417 -0.556583  1.465583   
9     148.800000  2300.308533 -1.408200 -0.398133 -0.449200  1.441667   
10    147.862997  2498.827111 -2.461520 -1.027493  0.429317  1.762029   
11     80.707327   545.332460 -7.666564 -7.226145 -0.820269  1.032728   
12    144.025517   700.013049  1.232655  1.619793  0.615690 -0.437517   
13    143.812000   898.519567  1.313350  1.639600  0.668200 -0.240600   
14    143.731667  1098.499517  1.386250  1.759000  0.654167 -0.083000   
15    143.661818  1299.602800  1.507091  1.935545  0.612909  0.041364   
16    143.618000  1502.215590 -0.981500 -0.651800 -0.465200  1.357800   
17    143.592727  1700.922045 -1.474636 -0.907818 -0.531818  1.480182   
18    143.550000  1899.170618 -1.633273 -0.965273 -0.587727  1.506455   

     bpi35_x   bpi38_x   bpi43_z   bpi45_z   bpi46_z   bpi56_x  label  
0  -0.376128  0.817139  0.796814 -0.565724  0.281941  3.760189      1  
1   3.208552 -4.715621 -0.342724 -3.750552 -2.198448 -0.811759      2  
2   3.614263 -5.371632 -0.401105 -3.242789 -1.792000 -0.889579      2  
3   4.168636 -6.034455 -0.397727 -2.930727 -1.555727 -1.063182      2  
4   4.596300 -6.567900 -0.380400 -2.715600 -1.405700 -1.264400      3  
5   1.924600 -1.496000 -0.129200 -1.178200 -0.032300 -0.737900      3  
6   0.950100 -0.772900 -0.227000 -0.860600  0.275300 -0.657000      3  
7   0.700364 -0.526364 -0.238636 -0.882818  0.263727 -0.786455      3  
8   0.463833 -0.565417 -0.244833 -0.912750  0.231417 -0.647750      4  
9   0.613200 -1.124600 -0.318800 -0.908600  0.251467 -0.469933      4  
10  1.153034 -0.866371  2.450866 -0.230293  0.234600  0.763579      4  
11  0.013750  0.452209  0.971554 -0.552409  0.175465  3.994206      1  
12  3.330345 -4.846552 -0.153034 -3.706552 -2.305793 -0.495586      2  
13  3.817450 -5.495050 -0.213850 -3.225250 -1.913050 -0.565150      2  
14  4.329583 -6.147667 -0.216667 -2.912500 -1.679583 -0.732917      2  
15  4.688818 -6.647909 -0.200818 -2.704727 -1.528636 -0.919000      3  
16  1.960400 -1.386600  0.014400 -1.088700 -0.083200 -0.391500      3  
17  1.118636 -0.861727 -0.036182 -0.837000  0.159909 -0.324273      3  
18  0.856364 -0.616727 -0.038364 -0.862091  0.148727 -0.443909      3

In [33]:
#Features+labels.
A = dataset.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11]]
B = dataset.iloc[:,12].values

In [34]:
A

beam_current  beam_energy    bpi2_x    bpi3_x   bpi27_z   bpi32_z  \
0     123.515023   545.320370 -7.498176 -7.092416 -0.762908  0.980314   
1     149.536207   699.055126  1.671586  1.991034  0.693276 -0.484345   
2     149.258421   897.739982  1.756947  2.027000  0.747211 -0.290421   
3     149.161818  1098.674273  1.827727  2.145818  0.733636 -0.134636   
4     149.102000  1298.582450  1.971600  2.352600  0.691200 -0.013800   
5     149.019000  1499.223220 -0.414300 -0.163000 -0.346000  1.257700   
6     148.968000  1699.855480 -1.010300 -0.511400 -0.474600  1.432500   
7     148.920909  1900.979145 -1.150182 -0.566000 -0.517727  1.461091   
8     148.884167  2100.929525 -1.359833 -0.617417 -0.556583  1.465583   
9     148.800000  2300.308533 -1.408200 -0.398133 -0.449200  1.441667   
10    147.862997  2498.827111 -2.461520 -1.027493  0.429317  1.762029   
11     80.707327   545.332460 -7.666564 -7.226145 -0.820269  1.032728   
12    144.025517   700.013049  1.232655  1.619793  0.615690 -0.437517   
13    143.812000   898.519567  1.313350  1.639600  0.668200 -0.240600   
14    143.731667  1098.499517  1.386250  1.759000  0.654167 -0.083000   
15    143.661818  1299.602800  1.507091  1.935545  0.612909  0.041364   
16    143.618000  1502.215590 -0.981500 -0.651800 -0.465200  1.357800   
17    143.592727  1700.922045 -1.474636 -0.907818 -0.531818  1.480182   
18    143.550000  1899.170618 -1.633273 -0.965273 -0.587727  1.506455   

     bpi35_x   bpi38_x   bpi43_z   bpi45_z   bpi46_z   bpi56_x  
0  -0.376128  0.817139  0.796814 -0.565724  0.281941  3.760189  
1   3.208552 -4.715621 -0.342724 -3.750552 -2.198448 -0.811759  
2   3.614263 -5.371632 -0.401105 -3.242789 -1.792000 -0.889579  
3   4.168636 -6.034455 -0.397727 -2.930727 -1.555727 -1.063182  
4   4.596300 -6.567900 -0.380400 -2.715600 -1.405700 -1.264400  
5   1.924600 -1.496000 -0.129200 -1.178200 -0.032300 -0.737900  
6   0.950100 -0.772900 -0.227000 -0.860600  0.275300 -0.657000  
7   0.700364 -0.526364 -0.238636 -0.882818  0.263727 -0.786455  
8   0.463833 -0.565417 -0.244833 -0.912750  0.231417 -0.647750  
9   0.613200 -1.124600 -0.318800 -0.908600  0.251467 -0.469933  
10  1.153034 -0.866371  2.450866 -0.230293  0.234600  0.763579  
11  0.013750  0.452209  0.971554 -0.552409  0.175465  3.994206  
12  3.330345 -4.846552 -0.153034 -3.706552 -2.305793 -0.495586  
13  3.817450 -5.495050 -0.213850 -3.225250 -1.913050 -0.565150  
14  4.329583 -6.147667 -0.216667 -2.912500 -1.679583 -0.732917  
15  4.688818 -6.647909 -0.200818 -2.704727 -1.528636 -0.919000  
16  1.960400 -1.386600  0.014400 -1.088700 -0.083200 -0.391500  
17  1.118636 -0.861727 -0.036182 -0.837000  0.159909 -0.324273  
18  0.856364 -0.616727 -0.038364 -0.862091  0.148727 -0.443909

In [35]:
B

array([1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 1, 2, 2, 2, 3, 3, 3, 3],
      dtype=int64)

In [36]:
#Dividing the data into train and test set.
from sklearn.model_selection import train_test_split
A_train, A_test, B_train, B_test = train_test_split(A, B, test_size = 0.25, random_state = 0)

In [37]:
#Used one vs rest classifier approach for multi class classification.
model = SVC(gamma='auto',random_state=0,kernel="poly")
ovr = OneVsRestClassifier(model)

#fit model to training data
ovr.fit(A_train, B_train)

#Predications
ovr_pred = ovr.predict(A_test)

#Adding Predictions to Test Dataset
ovr_df = A_test.copy()
ovr_df.insert(12,"Actual",B_test, True)
ovr_df.insert(13,"Predicted",ovr_pred, True)

In [38]:
ovr_df.head()

beam_current  beam_energy    bpi2_x    bpi3_x   bpi27_z   bpi32_z  \
10    147.862997  2498.827111 -2.461520 -1.027493  0.429317  1.762029   
1     149.536207   699.055126  1.671586  1.991034  0.693276 -0.484345   
8     148.884167  2100.929525 -1.359833 -0.617417 -0.556583  1.465583   
18    143.550000  1899.170618 -1.633273 -0.965273 -0.587727  1.506455   
14    143.731667  1098.499517  1.386250  1.759000  0.654167 -0.083000   

     bpi35_x   bpi38_x   bpi43_z   bpi45_z   bpi46_z   bpi56_x  Actual  \
10  1.153034 -0.866371  2.450866 -0.230293  0.234600  0.763579       4   
1   3.208552 -4.715621 -0.342724 -3.750552 -2.198448 -0.811759       2   
8   0.463833 -0.565417 -0.244833 -0.912750  0.231417 -0.647750       4   
18  0.856364 -0.616727 -0.038364 -0.862091  0.148727 -0.443909       3   
14  4.329583 -6.147667 -0.216667 -2.912500 -1.679583 -0.732917       2   

    Predicted  
10          4  
1           2  
8           3  
18          3  
14          2

In [39]:
#Showing actual and predicted values in tabular format.
ovr_df

beam_current  beam_energy    bpi2_x    bpi3_x   bpi27_z   bpi32_z  \
10    147.862997  2498.827111 -2.461520 -1.027493  0.429317  1.762029   
1     149.536207   699.055126  1.671586  1.991034  0.693276 -0.484345   
8     148.884167  2100.929525 -1.359833 -0.617417 -0.556583  1.465583   
18    143.550000  1899.170618 -1.633273 -0.965273 -0.587727  1.506455   
14    143.731667  1098.499517  1.386250  1.759000  0.654167 -0.083000   

     bpi35_x   bpi38_x   bpi43_z   bpi45_z   bpi46_z   bpi56_x  Actual  \
10  1.153034 -0.866371  2.450866 -0.230293  0.234600  0.763579       4   
1   3.208552 -4.715621 -0.342724 -3.750552 -2.198448 -0.811759       2   
8   0.463833 -0.565417 -0.244833 -0.912750  0.231417 -0.647750       4   
18  0.856364 -0.616727 -0.038364 -0.862091  0.148727 -0.443909       3   
14  4.329583 -6.147667 -0.216667 -2.912500 -1.679583 -0.732917       2   

    Predicted  
10          4  
1           2  
8           3  
18          3  
14          2

In [40]:
#Calculating accuracy of svm modal.
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(B_test,ovr_pred)
print(cm)
accuracy_score(B_test,ovr_pred)

[[2 0 0]
 [0 1 0]
 [0 1 1]]


0.8

In [41]:
B_train

array([3, 3, 3, 2, 3, 2, 4, 3, 3, 1, 2, 1, 3, 2], dtype=int64)

In [46]:
y_true = [4, 2, 4, 3, 2]
y_pred = [4, 2, 3, 3, 2]
f1_score(y_true, y_pred, average='micro')

0.8000000000000002

In [43]:
y_true = [4, 2, 4, 3, 2]
y_pred = [4, 2, 3, 3, 2]
precision_score(y_true, y_pred, average='macro')

0.8333333333333334